name: Docker build

on:
  push:
    branches:
      - "move-docker-release"

jobs:
  docker-publish-temp:
    # this should match the os version used by the "check bundle size" step in
    # pr.yml
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run installation
        run: npm ci
      # - name: Run build
      #   run: npm run build
      #   env:
      #     INFURA_KEY: ${{ secrets.INFURA_KEY }}

      # - name: Update documentation
      #   run: |
      #     npm run docs.build
      #     git add docs/**

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            trufflesuite/ganache
            ghcr.io/${{ github.repository}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@0522dcd2bf084920c411162fde334a308be75015

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@91cb32d715c128e5f0ede915cd7e196ab7799b83

      - name: hardcode env variables
        run: |
          echo "TAG=latest" >> $GITHUB_ENV
          echo "VERSION=v7.4.1" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./src/packages/ganache/Dockerfile
          push: true
          tags: ${{ format('trufflesuite/ganache:{0}, trufflesuite/ganache:v{1}', env.TAG, env.VERSION) }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64/v8,linux/amd64
          build-args: |
            INFURA_KEY=${{ secrets.INFURA_KEY }}
